apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-cluster-tls
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Release.Name }}-cluster-tls
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.ingress.host }}