apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ .Release.Name }}-{{ .Values.cluster.name }}-ingress
spec:
  entryPoints:
    - pgsql
  routes:
    - match: HostSNI(`{{ .Values.ingress.host }}`)
      services:
        - name: {{ .Release.Name }}-cluster-rw
          port: {{ .Values.ingress.servicePort }}