{{- $secret := lookup "v1" "Secret" .Release.Namespace (printf "%s-cluster-secret-su" .Release.Name) }}
{{- $now := now }}
{{- $createdAt := "" }}
{{- if $secret }}
  {{- $createdAt = (index $secret.metadata.annotations "created-at") }}
{{- end }}
{{- $rotate := false }}
{{- if $createdAt }}
  {{- /* Parse the created-at date and compare with now (Helm can't do date math, so use a workaround) */}}
  {{- if gt (sub ($now.Unix) ((date $createdAt).Unix)) (mul 10 24 60 60) }}
    {{- $rotate = true }}
  {{- end }}
{{- else }}
  {{- $rotate = true }}
{{- end }}

{{- if or (not $secret) $rotate }}
{{- $password := .Values.password | default (randAlphaNum 24) }}
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: {{ .Release.Name }}-cluster-secret-su
  annotations:
    created-at: "{{ $now | date "2006-01-02T15:04:05Z07:00" }}"
    helm.sh/resource-policy: keep
data:
  password: {{ $password | b64enc }}
  username: {{ (printf "%s-cluster-secret-su" .Release.Name) | b64enc }}
{{- end }}
