{{- $secret := lookup "v1" "Secret" .Release.Namespace (printf "%s-cluster-secret" .Release.Name) }}
{{- $now := now }}
{{- $createdAt := "" }}
{{- if $secret }}
  {{- $createdAt = (index $secret.metadata.annotations "created-at") }}
{{- end }}
{{- $rotate := false }}
{{- if $createdAt }}
  {{- /* Parse the created-at date and compare with now (Helm can't do date math, so use a workaround) */}}
  {{- if gt (sub ($now.Unix) ((date $createdAt).Unix)) (mul 10 24 60 60) }}
    {{- $rotate = true }}
  {{- end }}
{{- else }}
  {{- $rotate = true }}
{{- end }}

{{- if or (not $secret) $rotate }}
{{- $password := .Values.password | default (randAlphaNum 24) }}
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: {{ .Release.Name }}-cluster-secret
  annotations:
    created-at: "{{ $now | date "2006-01-02T15:04:05Z07:00" }}"
    helm.sh/resource-policy: keep
data:
  dbname: {{ "app" | b64enc }}
  host: {{ .Values.ingress.host | b64enc }}
  jdbc-uri: >-
    {{ printf "jdbc:postgresql://%s:5432/app?password=%s&user=app" .Values.ingress.host $password | b64enc }}
  password: {{ $password | b64enc }}
  pgpass: {{ printf "%s:%s:app:app:%s" .Values.ingress.host (default "5432" .Values.ServicePort) $password | b64enc }}
  port: {{ "5432" | b64enc }}
  uri: >-
    {{ printf "postgresql://app:%s@%s:5432/app" $password .Values.ingress.host | b64enc }}
  user: {{ "app" | b64enc }}
  username: {{ "app" | b64enc }}
{{- end }}
